In [1]:
import sys

# 1. Defina o caminho absoluto ou relativo da pasta onde está o seu código Python
sys.path.insert(1, '../src')

In [2]:
from utils import *
from preprocessing import *
from help import *

In [3]:
arquivo = '../data/raw/telecon.csv'
df = carregar_csv(caminho=arquivo)

verificar_dataframe(df=df)

,customerID,Genero,Idoso,Casado,Dependents,Tempo_como_Cliente,PhoneService,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Tipo_Contrato,PaymentMethod,Pagamento_Mensal,Total_Pago,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,DSL,No,No,No,Month-to-month,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,DSL,Yes,No,No,One year,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,DSL,Yes,No,No,Month-to-month,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,DSL,Yes,Yes,No,One year,Bank transfer (automatic),NaN,1840.75,No
4,9237-HQITU,NaN,0,No,No,2,Yes,Fiber optic,No,No,No,Month-to-month,Electronic check,NaN,151.65,Yes

In [4]:
novo_df = df.copy()

In [5]:
mostrar_percentual_nulos(df=novo_df)

Serão mostrados apenas as porcetagens de colunas com dados faltantes:
________________________________________________________________________________

Coluna: Genero | Dados faltantes: 0.48%

Pouco impacto. Pode remover linhas ou preencher com média, mediana ou moda.
________________________________________________________________________________

Coluna: PhoneService | Dados faltantes: 59.28%

A coluna possui muitos dados faltantes.
Considere remover a coluna.
Caso a variável seja booleana, dependendo do contexto, os valores nulos podem representar False.
________________________________________________________________________________

Coluna: Pagamento_Mensal | Dados faltantes: 13.00%

Dependendo do contexto, pode ser melhor imputar ou considerar remover a coluna.
________________________________________________________________________________

Coluna: Churn | Dados faltantes: 0.20%

Pouco impacto. Pode remover linhas ou preencher com média, mediana ou moda.
________________________________________________________________________________

In [6]:
info_tratar_nulos()

        Estratégias disponíveis:

        - remover_linhas
        - remover_coluna
        - media
        - mediana
        - moda

        Exemplo:

        tratar_nulos(df=nome_do_dataframe, coluna='nome_da_coluna', estrategia='media')

In [7]:
tratar_nulos(df=novo_df, coluna='Genero', estrategia='remover_linhas')

In [8]:
mostrar_percentual_nulos(df=novo_df)

Serão mostrados apenas as porcetagens de colunas com dados faltantes:
________________________________________________________________________________

Coluna: PhoneService | Dados faltantes: 59.57%

A coluna possui muitos dados faltantes.
Considere remover a coluna.
Caso a variável seja booleana, dependendo do contexto, os valores nulos podem representar False.
________________________________________________________________________________

Coluna: Pagamento_Mensal | Dados faltantes: 12.58%

Dependendo do contexto, pode ser melhor imputar ou considerar remover a coluna.
________________________________________________________________________________

In [9]:
# tratar_nulos(df=novo_df, coluna='PhoneService', estrategia='remover_coluna')

novo_df['PhoneService'] = novo_df['PhoneService'].fillna('No')

In [10]:
mostrar_percentual_nulos(df=novo_df)

Serão mostrados apenas as porcetagens de colunas com dados faltantes:
________________________________________________________________________________

Coluna: Pagamento_Mensal | Dados faltantes: 12.58%

Dependendo do contexto, pode ser melhor imputar ou considerar remover a coluna.
________________________________________________________________________________

In [11]:
novo_df.dtypes

customerID                str
Genero                    str
Idoso                   int64
Casado                    str
Dependents                str
Tempo_como_Cliente      int64
PhoneService              str
Servico_Internet          str
Servico_Seguranca         str
Suporte_Tecnico           str
StreamingTV               str
Tipo_Contrato             str
PaymentMethod             str
Pagamento_Mensal      float64
Total_Pago            float64
Churn                     str
dtype: object

In [12]:
info_converter_dados()

        Estratégias disponíveis para conversão de dados:

        - int64
            Converte valores inteiros.
            Exemplo: 1, 2, 3

        - float64
            Converte valores decimais.
            Exemplo: 10.5, 7.8

        - string
            Converte valores para texto.

        - bool
            Converte valores booleanos.
            Exemplo: True ou False

        - datetime
            Converte valores para data.
            Exemplo: 2025-01-01

        - category
            Converte valores categóricos para otimizar memória.
            Muito útil para colunas com poucos valores únicos.

        Exemplo de uso:

        novo_df = converter_dados(df=nome_do_dataframe, coluna='nome_da_coluna', estrategia='datetime')

In [13]:
novo_df['Tempo_como_Cliente'] = (novo_df['Tempo_como_Cliente'].replace(0, 1))

novo_df['Pagamento_Mensal'] = novo_df['Total_Pago'] / novo_df['Tempo_como_Cliente']

In [14]:
novo_df = mapear_coluna(df=novo_df,coluna='Churn',mapeamento={'Yes': 1,'No': 0})

In [15]:
novo_df.head()

,customerID,Genero,Idoso,Casado,Dependents,Tempo_como_Cliente,PhoneService,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Tipo_Contrato,PaymentMethod,Pagamento_Mensal,Total_Pago,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,DSL,No,No,No,Month-to-month,Electronic check,29.850000,29.85,0
1,5575-GNVDE,Male,0,No,No,34,Yes,DSL,Yes,No,No,One year,Mailed check,55.573529,1889.50,0
2,3668-QPYBK,Male,0,No,No,2,Yes,DSL,Yes,No,No,Month-to-month,Mailed check,54.075000,108.15,1
3,7795-CFOCW,Male,0,No,No,45,No,DSL,Yes,Yes,No,One year,Bank transfer (automatic),40.905556,1840.75,0
16,8191-XWSZG,F,0,No,No,52,Yes,No,No internet service,No internet service,No internet service,One year,Mailed check,19.672115,1022.95,0

In [16]:
mostrar_percentual_nulos(df=novo_df)

Serão mostrados apenas as porcetagens de colunas com dados faltantes:
________________________________________________________________________________
Não existe nenhuma coluna com dados faltantes.